name: CPP Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testbranches: ['release','master']

    steps:
      - uses: actions/checkout@v2

      - name: Apt update
        run: sudo apt update
        
      - name: Customize git
        run: |
          git submodule update --init --recursive
        
      - name: Install prerequisites
        run: |
          sudo apt install cmake g++ libeigen3-dev fakeroot
          
      - name: Build & install DQRobotics (${{ matrix.testbranches }})
        run: |
          git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp
          cd cpp
          sh .github/scripts/ubuntu/install_prerequisites.sh
          sh .github/scripts/ubuntu/build.sh
          sh .github/scripts/ubuntu/install.sh
          cd ..
          
      - name: Build & install cpp-interface-vrep
        run: |
          git checkout 
          chmod +x debian/rules
          fakeroot debian/rules clean
          fakeroot debian/rules build
          fakeroot debian/rules binary
          cd ..
          sudo apt install ./*.deb
          
      - name: Clone cpp-examples (${{ matrix.testbranches }})
        run: git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp-examples.git
          
      - name: Build examples
        run: |
          cd cpp-examples
          chmod +x .build_vrep.sh
          ./.build_vrep.sh
